### ISSUE TITLE
Change the context in the serve command

### ISSUE THREAD

**Issue by jpaniorte** [lyra/openapi-dev-tool#6]
Hello

I'm trying to publish the spec embedded in a docker container and consumed through a proxy reverse with nginx and I'm having trouble changing the context.

My nginx conf:

```
location /spec/mycontext {
        ....
        proxy_pass http://specip:3000
}
```

Is there a way to specify the context on openapi-dev-tool serve command for /sepc/mycontext?

Thank you very much in advance

**Comment by gigaga** [comment]
Hi @jpaniorte ,

First, thanks for your message, however, your issue is about nginx configuration, not about openapi-dev-tool.
You could find some help by visiting [nginx forum](https://forum.nginx.org/), or [official documentation](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).

Regards,

**Comment by jpaniorte** [comment]
Hi @gigaga,

Sorry if i'm confused, i'm not an expert in nodejs or express. Is it not possible to change the url base directly in express in all routes and public files? For example, change in server.js:
````
 app.get('/swagger-ui', viewersMiddleware.swaggerUI);
 app.get('/redoc', viewersMiddleware.redoc);
 app.get('/', viewersMiddleware.home);
````
for: 
````
 app.get('/spec/mycontext/swagger-ui', viewersMiddleware.swaggerUI);
 app.get(/spec/mycontext'/redoc', viewersMiddleware.redoc);
 app.get('/spec/mycontext/', viewersMiddleware.home);
````

If this is feasible, we can extract '/spec/mycontext' into a variable in the configuration file:

```
{
    "baseUrl": "/",
    "folder": "./specs",              // Root folder where the specifications are stored
    "specs": [  ]
}
```

And change all `app.get()` with `app.get(config.baseURL + '/swagger-ui, viewersMiddleware.swaggerUI);'`

PS: If this is not possible to do, no problem, there are other options (https://serverfault.com/questions/932628/how-to-handle-relative-urls-correctly-with-a-nginx-reverse-proxy)

**Comment by gigaga** [comment]
Hi @jpaniorte ,

Sorry for my late answer :( 
Currently, it is not possible to change path context of viewers (swagger / redoc) by configuration. For my part, this new feature would be unneeded because as mentioned by you, we can easily add a reverse proxy in frontal to be able to access to viewers from any url.

Regards,
